insert into _User (user_id, username, password, role) VALUES ('99995', 'customer', 'password', 'CUSTOMER');
insert into _User (user_id, username, password, role) VALUES ('99999', 'trainer', 'password', 'TRAINER');

insert into trainer (id, first_name, last_name, role, bio, rating, img, price, motto, background, location, years_of_exp) VALUES ('99996', 'tony', 'stark', 'TRAINER', 'IRON MAN', 3, 'https://cdn.vox-cdn.com/thumbor/UjJJtbVjzjURf6oiXSa0SomaEfU=/0x0:3000x1779/1200x800/filters:focal(1204x216:1684x696)/cdn.vox-cdn.com/uploads/chorus_image/image/59606327/ktokatitmir0.0.jpg', 100.00, 'Just do it', 'I own Some factory', 'New York', 9);
insert into trainer (id, first_name, last_name, role, bio, rating, img, price, motto, background, location, years_of_exp) VALUES ('99997', 'jamie', 'dimon', 'TRAINER', 'CEO', 4, 'https://g.foolcdn.com/editorial/images/700519/jamie-dimon-jpmorgan.png', 80.00, 'Just do it', 'I own a bank', 'New York', 2);
insert into trainer (id, first_name, last_name, role, bio, rating, img, price, motto, background, location, years_of_exp) VALUES ('99998', 'mark', 'ruffalo', 'TRAINER', 'The Hulk', 2, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvEmbAzzleQ9lakE0nuGCl6e-S9QInt1ZkaQ&usqp=CAU', 90.00, 'Just do it', 'I own chemicals', 'New York', 3);
insert into trainer (id, first_name, last_name, role, bio, rating, img, price, motto, background, location, years_of_exp) VALUES ('99999', 'tom', 'cruise', 'TRAINER', 'TOP GUN', 5, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN8Y6IKdRegpmGDa7EX-haO50vYiFx07gA3g&usqp=CAU', 100.00, 'Just do it', 'I own everyone', 'New York', 15);
insert into trainer (id, first_name, last_name, role, bio, rating, img, price, motto, background, location, years_of_exp) VALUES ('99995', 'christian', 'bale', 'TRAINER', 'BAT MAN', 5, 'https://images.immediate.co.uk/production/volatile/sites/3/2020/09/Batman-Begins-f677ee0.jpg?quality=90&resize=980,654', 100.00, 'Just do it', 'I own everyone', 'Arkansas', 7);
insert into trainer (id, first_name, last_name, role, bio, rating, img, price, motto, background, location, years_of_exp) VALUES ('99994', 'ryan', 'raynold', 'TRAINER', 'DEAD POOL', 5, 'https://www.regmovies.com/magnoliaPublic/dam/jcr:5b130960-68ca-4cfe-8659-6c1b5b17ff07/Deadpool01.jpg', 10.00, 'Just do it', 'I own everyone', 'Florida', 15);
insert into trainer (id, first_name, last_name, role, bio, rating, img, price, motto, background, location, years_of_exp) VALUES ('99993', 'joaquin', 'Phoenix', 'TRAINER', 'JOKER', 5, 'https://assets1.ignimgs.com/2019/08/28/joker-poster-1567009838218.jpg', 30.00, 'Just do it', 'I own everyone', 'New York', 5);
insert into trainer (id, first_name, last_name, role, bio, rating, img, price, motto, background, location, years_of_exp) VALUES ('99992', 'arthur', 'conan doyle', 'TRAINER', 'SHERLOCK', 5, 'https://s26162.pcdn.co/wp-content/uploads/sites/3/2021/08/shadow-sherlock.jpg', 10000.00, 'Just do it', 'I own everyone', 'New York', 5);
insert into trainer (id, first_name, last_name, role, bio, rating, img, price, motto, background, location, years_of_exp) VALUES ('99991', 'bruce', 'lee', 'TRAINER', 'BRUCE LEE', 5, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdk64HWnmFfqAmBfbMH3lZ_8UniZdQZv6nCw&usqp=CAU', 10000.00, 'Be water, my friend.', 'I own everyone', 'New York', 5);
insert into trainer (id, first_name, last_name, role, bio, rating, img, price, motto, background, location, years_of_exp) VALUES ('99990', 'tom', 'dimon', 'TRAINER', 'CEO', 5, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN8Y6IKdRegpmGDa7EX-haO50vYiFx07gA3g&usqp=CAU', 100.00, 'Just do it', 'I own everyone', 'New York', 5);
insert into trainer (id, first_name, last_name, role, bio, rating, img, price, motto, background, location, years_of_exp) VALUES ('99989', 'tom', 'dimon', 'TRAINER', 'CEO', 5, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN8Y6IKdRegpmGDa7EX-haO50vYiFx07gA3g&usqp=CAU', 100.00, 'Just do it', 'I own everyone', 'New York', 5);

insert into customer (id, first_name, last_name, role, goal, age, height, weight, trainer_id) VALUES ('99995', 'dead', 'pool', 'CUSTOMER', 'lost weight', 33, 172, 150, 99999);
insert into customer (id, first_name, last_name, role, goal, age, height, weight, trainer_id) VALUES ('99994', 'iron', 'pool', 'CUSTOMER', 'lost weight', 133, 112, 110, 99999);
